**Importing packages that we need**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from numba import jit, njit, vectorize

**Setting up the Monte Carlo method for a NxN lattice:**

In [11]:
#function that defines that inital state for the lattice calling a random number generator
@jit
def StateInitalize(N):
    #NXN number of spins
    Lattice = np.zeros((N,N))
    for i in range(N):
        for l in range(N):
            randNum = np.random.random()
            if randNum < 0.5:
                Lattice[i,l] = int(-1)
            else:
                Lattice[i,l] = int(1)
                
    return Lattice

In [16]:
A = StateInitalize(4)
print(A)

[[-1. -1. -1.  1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1.  1.]
 [-1.  1. -1.  1.]]


In [ ]:
def MonteCarloIsing(InitialState,NumOfCycles):
    MC = NumOfCycles
    for i in range(MC):
        